### PR TITLE
Update chrome.manifest

### PR DESCRIPTION
**Pull request by ovari**

### CODE REVIEW

**Comment by cleidigh** [comment]
@ovari 
Hey, I just saw your e-mail, when I looked at your request it was done almost two months ago ! 
I don't know  why I did not get notifications. sorry about that.
I should be able to merge these. 
question: it looks like the manifest changes are just ordering, is this sort of accepted as the preferred order?
cheers

**Comment by ovari** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Chrome_Registration

**Comment by cleidigh** [comment]
@ovari 
I'm going to roll these into a new branch for the next Release , I like to merge branches at inflection points.
thanks for the link above

**Comment by ovari** [comment]
Can you please merge these in your master or other branch so we can delete the fork of your repository? Thank you

**Comment by cleidigh** [comment]
WIP branch for next Release

**Comment by cleidigh** [comment]
merge manually

**Comment by ovari** [comment]
Thank you

**Pull request closed without merging**
